### ISSUE TITLE
Documentation and other links point to no longer valid `mamba-org` urls

### ISSUE THREAD

**Issue by synapticarbors** [conda-incubator/rattler#803]
I noticed that the documentation links and a bunch of others all still point to the `mamba-org.github.io` and are therefore broken since the project moved to `conda-incubator`. I'd be happy to submit a PR to fix this, but I was wondering if I should wait for the decision on https://github.com/conda-incubator/rattler/issues/799, since it will then change again.

**Comment by Hofer-Julian** [comment]
> I noticed that the documentation links and a bunch of others all still point to the `mamba-org.github.io` and are therefore broken since the project moved to `conda-incubator`. I'd be happy to submit a PR to fix this, but I was wondering if I should wait for the decision on #799, since it will then change again.

If you don't mind, fixing the links would be appreciated. It is not clear yet when rattler will move again

**Comment by synapticarbors** [comment]
Looks like https://github.com/conda-incubator/rattler/commit/01be6ae676f240e1cea21cb669fa15e0abdc2a65 beat me to it. Thanks @baszalmstra
